---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-e2e-org1
  namespace: hyperledger
  labels:
    app: chaincode-e2e-org1
spec:
  selector:
    matchLabels:
      app: chaincode-e2e-org1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-e2e-org1
    spec:
      containers:
        - image: chaincode/e2e:1.0
          name: chaincode-e2e-org1
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_CCID
              value: "e2e:0057a2c8e2731b2c09a75f1a6eb79ca078c7936f21fc8c0995b51df3a18f853e"
            - name: CHAINCODE_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
