--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: chaincode-fabcar-org2
  namespace: hyperledger
  labels:
    app: chaincode-fabcar-org2
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-fabcar-org2
